exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, README.md readme.md]
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
rdiscount:
    extensions: [smart]
sass:
  sass_dir: bower_components

authors:
  samvevang:
    display_name: Sam Vevang
    first_name: Sam
    email: sam.vevang@gmail.com
    github: svevang
    bio: I hack on Ruby, Python and Javascript
    avatar: http://www.gravatar.com/avatar/9aefff1a32b4263a84441fc387996e7a?s=200
  michaelkirk:
    display_name: Michael Kirk
    first_name: Michael
    email: michael.john.kirk@gmail.com
    github: michaelkirk
    bio: I craft code, build teams, and manage projects.
    avatar: http://www.gravatar.com/avatar/28b6612d548d24ff57361dac58ac3fee?s=200
